# Generated by Django 2.0.2 on 2018-03-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('resolution_x', models.IntegerField(default=4096)),
                ('resolution_y', models.IntegerField(default=2304)),
                ('has_alpha', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('folder', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='footage',
            name='project',
            field=models.ForeignKey(on_delete='cascade', to='app.Project'),
        ),
    ]
