# Generated by Django 2.0.2 on 2018-03-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180318_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='take',
            name='motion',
        ),
        migrations.RemoveField(
            model_name='take',
            name='project',
        ),
        migrations.RemoveField(
            model_name='footage',
            name='take',
        ),
        migrations.AddField(
            model_name='footage',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footage',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='footage',
            name='motion',
            field=models.ForeignKey(null=True, on_delete='cascade', to='app.Motion'),
        ),
        migrations.AddField(
            model_name='footage',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='footage',
            name='project',
            field=models.ForeignKey(null=True, on_delete='cascade', to='app.Project'),
        ),
        migrations.AddField(
            model_name='footage',
            name='rendered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='footage',
            name='filename',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Take',
        ),
    ]
