# Generated by Django 2.0.2 on 2018-03-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180318_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='footage',
            name='filename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='footage',
            name='motion',
            field=models.ForeignKey(default=None, on_delete='cascade', to='app.Motion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footage',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='footage',
            name='project',
            field=models.ForeignKey(default=None, on_delete='cascade', to='app.Project'),
            preserve_default=False,
        ),
    ]
