# Generated by Django 2.0.2 on 2018-03-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_marketplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('footage', models.ForeignKey(on_delete='cascade', to='app.Footage')),
                ('marketplace', models.ForeignKey(on_delete='cascade', to='app.Marketplace')),
            ],
        ),
    ]
