# Generated by Django 2.0.2 on 2018-03-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='marketplace',
            field=models.ForeignKey(on_delete='cascade', to='app.Marketplace'),
        ),
    ]
