# Generated by Django 2.0.2 on 2018-03-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180318_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='marketplace',
            field=models.ForeignKey(on_delete='cascade', to='app.Marketplace'),
        ),
    ]
