# Generated by Django 2.0.2 on 2018-03-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180318_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='marketplace',
            field=models.ForeignKey(on_delete='cascade', to='app.Marketplace'),
        ),
    ]
