# Generated by Django 2.0.2 on 2018-03-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180318_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='footage',
            name='keywords_raw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='marketplace',
            field=models.ForeignKey(on_delete='cascade', to='app.Marketplace'),
        ),
    ]
