# Generated by Django 2.0.2 on 2018-03-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180318_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='footage',
            name='filename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='footage',
            name='keywords_raw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footage',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='marketplace',
            field=models.ForeignKey(on_delete='cascade', to='app.Marketplace'),
        ),
    ]
