# Generated by Django 2.0.2 on 2018-03-18 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180318_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='footage',
            name='motion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Motion'),
        ),
        migrations.AlterField(
            model_name='footage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='footage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Footage'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='marketplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Marketplace'),
        ),
        migrations.AddField(
            model_name='project',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Theme'),
        ),
    ]
